### ISSUE TITLE
4.1.2 breaks usage in Cloudflare Worker

### ISSUE THREAD

**Issue by leviwolfe** [fauna/faunadb-js#447]
Specifying `"faunadb": "4.1.1"` (along with the [known issue workaround](https://github.com/fauna/faunadb-js#using-with-cloudflare-workers)) in my `package.json` dependencies is working while `"faunadb": "^4.1.2"` unfortunately has the following error when attempting to create a faunadb client:

```"navigator is not defined"
ReferenceError: navigator is not defined
    at Object.getBrowserDetails (worker.js:1:2773)
    at worker.js:6:5260
    at new s (worker.js:6:5461)
    at new d (worker.js:6:17008)
    at new a (worker.js:6:33478)
    at s (worker.js:6:33984)
    at Proxy.e.r (worker.js:6:14246)
    at worker.js:6:34805
```

Sorry I'm not familiar enough with runtime de-obfuscating stack traces in Cloudflare Workers yet. I suspect this is new as of #436.

**Comment by alizahid** [comment]
Also breaks when using with Next.js locally. However, seems to be working when deployed in production to Vercel. Although I have a feeling that it's pulling the older version from the cache when building in production.

My error, however, is different. I'm able to create a client and do queries, but when doing a query that creates a document, I get this error;

```
Error [ERR_HTTP2_GOAWAY_SESSION]: New streams cannot be created after receiving a GOAWAY
    at new NodeError (node:internal/errors:329:5)
    at ClientHttp2Stream.requestOnConnect (node:internal/http2/core:693:17)
    at node:internal/http2/core:1755:68
    at Array.forEach (<anonymous>)
    at ClientHttp2Session.<anonymous> (node:internal/http2/core:1755:11)
    at Object.onceWrapper (node:events:476:26)
    at ClientHttp2Session.emit (node:events:381:22)
    at emit (node:internal/http2/core:324:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_HTTP2_GOAWAY_SESSION'
}
```

**Comment by RaymondMoay** [comment]
I'm having a similar error as @alizahid on NextJS. I can't do a simple read.

An API endpoint like this:

```
export default async (req, res) => {
    try {
      const doc = await db.query(
        q.Get(q.Ref(q.Collection("tweets"), req.query.id))
      );
      res.status(200).json(doc);
    } catch (e) {
      res.status(500).json({ error: e.message });
    }
  };
```

leads to an error like this:

`
{
    "error": "New streams cannot be created after receiving a GOAWAY"
}
`

Using 4.1.1 works.

**Comment by kristhetraj** [comment]
Hello, I am getting the same error as above:

```
err Error [ERR_HTTP2_GOAWAY_SESSION]: New streams cannot be created after receiving a GOAWAY
    at ClientHttp2Stream.requestOnConnect (internal/http2/core.js:664:17)
    at internal/http2/core.js:1676:53
    at Array.forEach (<anonymous>)
    at ClientHttp2Session.<anonymous> (internal/http2/core.js:1676:38)
    at Object.onceWrapper (events.js:422:26)
    at ClientHttp2Session.emit (events.js:327:22)
    at emit (internal/http2/core.js:295:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ERR_HTTP2_GOAWAY_SESSION'
```

Older versions of the lib works and using the CDN version works:   
<script src="https://cdn.jsdelivr.net/npm/faunadb@latest/dist/faunadb.js"></script>

**Comment by parkhomenko** [comment]
@kristhetraj @RaymondMoay @alizahid @leviwolfe Thanks for reporting this issue.
Could you try the latest 4.1.3 version. It should have been fixed there.

**Comment by kristhetraj** [comment]
Hello @parkhomenko, just tested it on version 4.1.3 and it looks good. Thanks for the quick turnaround.

**Comment by leviwolfe** [comment]
@parkhomenko I am still getting the `ReferenceError: navigator is not defined at Object.getBrowserDetails` error using 4.1.3 in a Cloudflare Worker.

**Comment by PierBover** [comment]
I'm also experiencing the issue with 4.1.3. The solution was to revert back to 4.1.1.

```
npm install faunadb@4.1.1
```

**Comment by fireridlle** [comment]
fixed at 4.2.0
fix confirmed by @PierBover at slack
